name: Build and Test Python App

on:
  push:
    branches: [ "develop", "feature" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repo
      uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        
    - name: Run Unit tests
      run: |
        pytest
